# Generated by Django 5.1 on 2024-09-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingPlatform', '0002_questionnaireresult_detailedanswer_delete_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresult',
            name='comfort_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='questionnaireresult',
            name='favorite_team',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='questionnaireresult',
            name='favorite_topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
